config/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard_clients/', views.dashboard_clients, name='dashboard_clients'),
    path('user_role/<int:pk>/', views.user_role, name='user_role'),
    path('profile_home/', views.profile_home, name='profile_home'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/<int:pk>/', views.profile_update, name='profile_update'),
    path('cardChange/<int:pk>', views.user_change_card, name='cardChange'),
    path('passChange/<int:pk>/', views.user_change_password, name='passChange'),
    path('addressChange/<int:pk>', views.user_change_address, name='addressChange'),
    path('user_delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('', views.user_login, name='user_login'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('general/', include('general.urls', namespace='general')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    # path('discounts/', include('discounts.urls', namespace='discounts')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls')),
    path('wishlists/', include('wishlists.urls', namespace='wishlists')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),      
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/accounts/models.py
from django.db import models
from .servises import upload_avatar_path
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField

# Create your models here.

class User(AbstractUser):

    CHOICE_ROLE = (
        ('client', 'CLIENT'),
        ('admin', 'ADMIN'),
    )

    CHOICE_CURRENCY = (
        ('uzs', 'UZS'),
        ('usd', 'USD'),
        ('rub', 'RUB'),
    )

    CHOICE_CITY = (
        ('tashkent', 'TASHKENT'),
        ('surxondaryo', 'SURXONDARYO'),
    )

    CHOICE_REGION = (
        ('olmazor', 'OLMAZOR'),
        ('chilonzor', 'CHILONZOR'),
        ('kumkurgan', 'KUMKURGAN'),
        ('termiz', 'TERMIZ')
    )

    email = models.EmailField('email address', unique=True)
    phonenumber = PhoneNumberField(null=True, blank=True, unique=True)
    avatar = models.ImageField(upload_to=upload_avatar_path, default='profile/defaultadmin/defaultadmin.png')
    user_currency = models.CharField(max_length=3, choices=CHOICE_CURRENCY, default=CHOICE_CURRENCY[0][0])
    about = models.TextField(blank=True, null=True)
    role = models.CharField(max_length=6, choices=CHOICE_ROLE, default=CHOICE_ROLE[0][0])

    # Address

    country = CountryField(blank=True, null=True)
    city = models.CharField(max_length=20, choices=CHOICE_CITY)
    region = models.CharField(max_length=100, choices=CHOICE_REGION)
    zip_code = models.PositiveIntegerField(blank=True, null=True)
    address1 = models.CharField(max_length=250, blank=True)

    # Card

    card_number = models.PositiveIntegerField(blank=True, null=True)
    card_date = models.DateField(blank=True, null=True)
    currency = models.CharField(max_length=3, choices=CHOICE_CURRENCY, default=CHOICE_CURRENCY[0][0])

    def __str__(self):
        return self.username
    
class UserDataOnDelete(models.Model):
    first_name = models.CharField('first name', max_length=150)
    last_name = models.CharField('last name', max_length=150)
    username = models.CharField(max_length=128)
    role = models.CharField(max_length=6, choices=User.CHOICE_ROLE, default=User.CHOICE_ROLE[0][0])

    def __str__(self) -> str:
        return self.username

config/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=128)
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password1')
        

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)
    
    def user_auth(self):
        user = authenticate(**self.cleaned_data)
        if user:
            return user
        return None

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        exclude = ('date_joined', 'last_login', 'groups', 'user_permissions')


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('avatar', 'username', 'first_name', 'last_name', 'about', 'user_currency', 'address1', 'phonenumber', 'email')

class UserCurrencyForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('user_currency',)

class UserCardChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('card_number', 'card_date', 'currency')

class UserChangePassword(forms.Form):
    password = forms.CharField(max_length=128)
    password1 = forms.CharField(max_length=128)
    password2 = forms.CharField(max_length=128)

class UserAddressForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('country', 'city', 'region', 'zip_code', 'address1')

class UserRoleForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('role',)

config/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib import messages
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.db.models import Q
from .forms import *
from .models import User
from django.core.files import File
from django.conf import settings


# Create your views here.

def user_register(request):

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():

            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            password1 = form.cleaned_data.get('password1')

            user = User.objects.filter(Q(username=username) | Q(email=email))
            
            if not user:
                if password == password1:
                    user = User(username = username, email=email)
                    user.set_password(password)
                    user.save()
                    return redirect('accounts:user_login')
                else:
                    messages.error(request, 'The password is not the same')
            else:
                messages.error(request, 'You are registered')
        else:
            messages.error(request, 'The form was filled in incorrectly')
    else:
        form = UserRegisterForm

    return render(request, 'sign_up.html', {'form':form})


def user_login(request):
    
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid() and form.user_auth():
            user = form.user_auth()
            login(request, user)
            return redirect('general:home')
        else:
            if form.errors:
                messages.error(request, form.errors)
            else:
                messages.error(request, 'You are not registered')
    else:
        form = UserLoginForm()

    return render(request, 'sign_in.html', {'form':form})


def password_reset_request(request):
    if request.method == 'POST':
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password_reset/password_reset_email.txt"
                    context = {
                        'email': user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'e_shop',
                        'uidb64': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user':user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, context)
                    try:
                        send_mail(subject ,email, 'mbpy2000@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found')
                    return redirect('/password_reset/done/')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name='password_reset/password_reset.html', context={'password_reset_form':password_reset_form})


def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')


def dashboard(request):
    user = request.user
    context = {
        'user': user,
    }
    return render(request, 'dashboard/dashboard_index.html', context)


def dashboard_clients(request):

    users = []
    for user in User.objects.all():
        if user.role == 'client':
            users.append(user)
    context = {
        'users': users,
    }

    return render(request, 'dashboard/clients.html', context)

def user_role(request, pk):
    user1 = User.objects.get(id=pk)
    users = []
    form = UserRoleForm()
    for user in User.objects.all():
        if user.role == 'client':
            users.append(user)

    if request.method == 'POST':
        form = UserRoleForm(request.POST, instance=user1)
        if form.is_valid():
            form.save()
            return redirect('accounts:dashboard_clients')
        else:
            messages.error(request, form.errors)
    
    context = {
        'user1':user1,
        'form':form,
        'users': users,
    }

    return render(request, 'dashboard/clients.html', context)

def profile_home(request):
    user = request.user
    context = {
        'user': user,
    }
    return render(request, 'profile/user_profile_index.html', context)


@login_required(login_url='accounts:user_login')
def profile(request):

    user = request.user
    currency_form = UserCurrencyForm(instance=user)
    card_form = UserCardChangeForm(instance=user)
    pass_form = UserChangePassword()
    address_form = UserAddressForm(instance=user)

    context = {
            'user': user,
            'card_form': card_form,
            'currency_form': currency_form,
            'pass_form': pass_form,
            'address_form': address_form,
        }

    return render(request, 'profile/user_profile.html', context)


def profile_update(request, pk):
    form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
            
    if form.is_valid():
        user = form.save(commit=False)
        if request.POST.get('delete_avatar'):
            form.cleaned_data['avatar'] = None
            user.avatar.save(
                'defaultadmin.png', File(open(settings.DEFAULT_AVATAR_URL, 'rb'))
            )
        user.save()
    else:
        messages.error(request, form.errors)

    return redirect('accounts:profile')


def user_change_card(request, pk):

    card1_form = UserCardChangeForm(request.POST, instance=request.user)
    if card1_form.is_valid():
        card1_form.save()
        messages.success(request, 'Card information has changed')
    else:
        messages.error(request, card1_form.errors)
    
    return redirect('accounts:profile')


def user_change_password(request, pk):
    
    pass_form = UserChangePassword(request.POST)
    if pass_form.is_valid():
        user = User.objects.get(username=request.user)
        if user.check_password(pass_form.cleaned_data['password']):
            if pass_form.cleaned_data['password1'] == pass_form.cleaned_data['password2']:
                user.set_password(pass_form.cleaned_data['password2'])
                user.save()
                messages.success(request, 'Password changed successfully!')
            else:
                messages.error(request, 'New passwords don\'t similar!')
        else:
            messages.error(request, 'The old password was entered incorrectly!')
    else:
        messages.error(request, pass_form.errors)
    
    return redirect('accounts:profile')


def user_change_address(request, pk):

    address_form = UserAddressForm(request.POST, instance=request.user)
    if address_form.is_valid():
        address_form.save()
        messages.success(request, 'Address changed successfully')
    else:
        messages.error(request, address_form.errors)
    
    return redirect('accounts:profile')



def user_delete(request, pk):
    
    user = get_object_or_404(User, id=pk)
    if request.POST:
        user.delete()
        return redirect('general:home')

    return render(request, 'user_delete.html')

config/accounts/templates/profile/page-error-404.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Pages / Not Found 404 - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.4.1
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <main>
    <div class="container">

      <section class="section error-404 min-vh-100 d-flex flex-column align-items-center justify-content-center">
        <h1>404</h1>
        <h2>The page you are looking for doesn't exist.</h2>
        <a class="btn" href="index.html">Back to home</a>
        <img src="assets/img/not-found.svg" class="img-fluid py-5" alt="Page Not Found">
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/vendor/chart.js/chart.min.js"></script>
  <script src="assets/vendor/echarts/echarts.min.js"></script>
  <script src="assets/vendor/quill/quill.min.js"></script>
  <script src="assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>

config/accounts/templates/profile/user_profile.html
{% extends 'profile/user_profile_base.html' %}
{% load static %}

{% block content %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'accounts:profile_home' %}">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">Profile</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-3">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

              <img src="{{user.avatar.url}}" alt="Profile" class="rounded-circle">
              <h2>{{user.first_name}} {{user.last_name}}</h2>
              <h3>{{user.get_role_display}}</h3>
              <div class="social-links mt-2">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="telegram"><i class="bi bi-telegram"></i></a>
              </div>
            </div>
            <div>
              {% if messages %}
                {% for message in messages %}
                    {{message|safe}}
                {% endfor %}
              {% endif %}
            </div>
          </div>

        </div>

        <div class="col-xl-9">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-card">Card Change</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Password Change</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-address">Address Change</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  <h5 class="card-title">About</h5>
                  <p class="small fst-italic">{{user.about}}</p>

                  <h5 class="card-title">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Full Name</div>
                    <div class="col-lg-9 col-md-8">{{user.first_name}} {{user.last_name}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Country</div>
                    <div class="col-lg-9 col-md-8">{{user.get_country_display}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Address</div>
                    <div class="col-lg-9 col-md-8">{{user.address1}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Phone</div>
                    <div class="col-lg-9 col-md-8">{{user.phonenumber}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div class="col-lg-9 col-md-8">{{user.email}}</div>
                  </div>

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">

                  <!-- Profile Edit Form -->
                  <form method='post' action="{% url 'accounts:profile_update' user.id %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                      <div class="col-md-8 col-lg-9">
                        <img src="{{user.avatar.url}}" alt="Profile">
                        <div class="pt-2">
                          <input name="avatar" type="file"  value="{{ user.avatar.url }}">
                          <a href="{{ user.avatar.url }}">{{ user.avatar.url }}</a>
                          <label>
                            <span class="btn btn-danger btn-sm"><i class="bi bi-trash"></i></span>
                            <input style="display: none;" name="delete_avatar" type="checkbox">
                          </label>
                        </div>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="UserName" class="col-md-4 col-lg-3 col-form-label">Username</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="username" type="text" class="form-control" id="userName" value="{{user.username}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="firstName" class="col-md-4 col-lg-3 col-form-label">First Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="first_name" type="text" class="form-control" id="first_name" value="{{user.first_name}}">
                      </div>
                    </div>
                    
                    <div class="row mb-3">
                      <label for="lastName" class="col-md-4 col-lg-3 col-form-label">Last Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="last_name" type="text" class="form-control" id="last_name" value="{{user.last_name}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="about" class="col-md-4 col-lg-3 col-form-label">About</label>
                      <div class="col-md-8 col-lg-9">
                        <textarea name="about" class="form-control" id="about" style="height: 100px">{{user.about}}</textarea>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="Country" class="col-md-4 col-lg-3 col-form-label">Currency</label>
                      <div class="col-md-8 col-lg-9">
                        {% for form in currency_form %}
                          {{form}}
                        {% endfor %}
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="Address" class="col-md-4 col-lg-3 col-form-label">Address</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="address1" type="text" class="form-control" id="Address````" value="{{user.address1}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="Phonenumber" class="col-md-4 col-lg-3 col-form-label">Phone</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="phonenumber" type="text" class="form-control" id="Phonenumber" value="{{user.phonenumber}}">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="Email" class="col-md-4 col-lg-3 col-form-label">Email</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="email" type="email" class="form-control" id="Email" value="{{user.email}}">
                      </div>
                    </div>

                    <div class="text-center">
                      <input type="submit" class="btn btn-primary" value="Save Changes">
                    </div>
                  </form><!-- End Profile Edit Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-change-card">

                  <!-- Settings Form -->
                  <form method = 'post' action="{% url 'accounts:cardChange' user.id %}">
                    {% csrf_token %}
                    {{card_form.as_p}}

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End settings Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-change-password">

                  <!-- Change Password Form -->
                  <form method='post' action="{% url 'accounts:passChange' user.id %}">
                    {% csrf_token %}
                    <div class="row mb-3">
                      <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="password" type="password" class="form-control" id="currentPassword">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="password1" type="password" class="form-control" id="newPassword">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="renewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="password2" type="password" class="form-control" id="renewPassword">
                      </div>
                    </div>

                    <div class="text-center">
                      <input type="submit" class="btn btn-primary" value="Change Password">
                    </div>
                  </form><!-- End Change Password Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-change-address">

                  <!-- Change Password Form -->
                  <form method='post' action="{% url 'accounts:addressChange' user.id %}">
                    {% csrf_token %}
                    {{address_form.as_p}}
                    <div class="text-center">
                      <input type="submit" class="btn btn-primary" value="Change Password">
                    </div>
                  </form><!-- End Change Password Form -->

                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

{% endblock content %}