config/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard_clients/', views.dashboard_clients, name='dashboard_clients'),
    path('user_role/<int:pk>/', views.user_role, name='user_role'),
    path('profile_home/', views.profile_home, name='profile_home'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/<int:pk>/', views.profile_update, name='profile_update'),
    path('cardChange/<int:pk>', views.user_change_card, name='cardChange'),
    path('passChange/<int:pk>/', views.user_change_password, name='passChange'),
    path('addressChange/<int:pk>', views.user_change_address, name='addressChange'),
    path('user_delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('', views.user_login, name='user_login'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('general/', include('general.urls', namespace='general')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    # path('discounts/', include('discounts.urls', namespace='discounts')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls')),
    path('wishlists/', include('wishlists.urls', namespace='wishlists')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),      
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/general/urls.py
from django.urls import path
from . import views

app_name = 'general'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop_product_search/', views.shop_product_search, name='shop_product_search'),
    path('product_search/', views.product_search, name="product_search"),
    path('category_search/<slug:slug>/', views.category_search, name="category_search"),
    path('product_detail/<slug:slug>/', views.product_detail, name="product_detail"),
    path('productItem_card/<slug:slug>/', views.productItem_card, name="productItem_card"),
    path('card/', views.card, name='card'),
    path('card_add/<slug:slug>/<int:quantity>/', views.card_add, name='card_add'),
    path('card_remove/<int:id>/', views.card_remove, name='card_remove'),
    path('card_update/<int:id>/', views.card_update, name='card_update'),
    path('card_clear/', views.card_clear, name='card_clear'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
]

config/wishlists/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist_add/<slug:slug>/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/<int:id>/', views.wishlist_delete, name='wishlist_delete'),
]

config/general/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class ShopAbout(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    create_date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

class ContactUs(models.Model):
    title = models.CharField(max_length=50)
    shop = models.ForeignKey(ShopAbout, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = PhoneNumberField(unique=True)

    def __str__(self) -> str:
        return self.title
    
class ContactQuery(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    subject = models.CharField(max_length=250)
    text = models.TextField()

    def __str__(self):
        return self.subject

config/general/forms.py
from django import forms
from .models import ShopAbout, ContactUs

class ShopAbout(forms.ModelForm):

    class Meta:
        model = ShopAbout
        fields = ('name', 'description')

class ContactUs(forms.ModelForm):

    class Meta:
        model = ContactUs
        fields = ('title', 'shop', 'address', 'email', 'email')

config/general/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum, Q
from django.contrib import messages
from decimal import Decimal
from deliveries.models import Delivery


from accounts.models import User
from .models import ShopAbout, ContactUs, ContactQuery
from products.models import *

# Create your views here.
@login_required
def home(request):
    user = request.user
    
    products = Product.objects.all()
    context = {
        'user': user,
        'products': products,
    }

    return render(request, 'index.html', context)

def shop(request):

    productItems = ProductItem.objects.all().order_by('price')
    total_count = productItems.aggregate(total_count=Sum('count_in_stock'))['total_count']

    colors = ProductColor.objects.annotate(
        product_count=Sum('productitem__count_in_stock'),
    )

    sizes = ProductSize.objects.annotate(
        product_count=Sum('productitem__count_in_stock'),
    )

    # Filter products

    request.session['filter'] = {}
    request.session['product_name'] = {}
    if bool(request.GET):
        for x, y in request.GET.items():
            if y == 'on' and x not in request.session['filter']:
                request.session['filter'][str(x)] = True

        if 'all_price' in request.GET:
            productItems = set(filter(lambda obj: obj.price, productItems))
        else:
            productitem = set()
            if '0_price_100' in request.GET:
                productitem = set(filter(lambda obj: 0 <= obj.price <= 100, productItems))
            if '100_price_200' in request.GET:
                productitem = set(filter(lambda obj: 100 <= obj.price <= 200, productItems)) | productitem
            if '200_price_300' in request.GET:
                productitem = set(filter(lambda obj: 200 <= obj.price <= 300, productItems)) | productitem
            if '300_price_400' in request.GET:
                productitem = set(filter(lambda obj: 300 <= obj.price <= 400, productItems)) | productitem
            if '400_price_more' in request.GET:
                productitem = set(filter(lambda obj: 400 <= obj.price, productItems)) | productitem
            productItems = productitem
        

        if 'all_color' in request.GET:
            productItems = set(filter(lambda obj: obj.color, productItems))
        else:
            cs = []
            for c in colors:
                if f'{c.name}' in request.GET:
                    cs.append(c.name)
            productItems = set(filter(lambda obj: obj.color.name in cs, productItems))
        
        if 'all_size' in request.GET:
            productItems = set(filter(lambda obj: obj.size, productItems))
        else:
            ss = []
            for s in sizes:
                if f'{s.size}' in request.GET:
                    ss.append(s.size)
            productItems = set(filter(lambda obj: obj.size.size in ss, productItems))
        

    # data_in_cashe = cache.get('productItems', False)
    # if not data_in_cashe:
    #     productItems = cache.set('productItems', productItems)

    productItems = list(productItems)
    productItems.sort(key=lambda obj: obj.price)
    for product in productItems:
        request.session['product_name'][str(product.title)] = product.title

    context = {
        'productItems': productItems,
        'colors': colors,
        'sizes': sizes,
        'total_count': total_count,
    }
    return render(request, 'shop.html', context)

def shop_product_search(request):
    productItems = ProductItem.objects.all().order_by('price')
    total_count = productItems.aggregate(total_count=Sum('count_in_stock'))['total_count']

    colors = ProductColor.objects.annotate(
        product_count=Sum('productitem__count_in_stock'),
    )

    sizes = ProductSize.objects.annotate(
        product_count=Sum('productitem__count_in_stock'),
    )
    # Search product
    if request.session['filter']:
        if 'q' in request.GET:
            q_list = []
            q = request.GET['q']
            for title in request.session['product_name']:
                if q.lower() in title.lower():
                    q_list.append(title)
            productItems = set(filter(lambda obj: obj.title in q_list, productItems))
    else:
        print('salom1')
        if 'q' in request.GET:
            q = request.GET['q']
            productItems = ProductItem.objects.filter(title__icontains=q)
    
    productItems = list(productItems)
    productItems.sort(key=lambda obj: obj.price)

    context = {
        'productItems': productItems,
        'colors': colors,
        'sizes': sizes,
        'total_count': total_count,
    }
    return render(request, 'shop.html', context)

def product_search(request):
    if 'q' in request.GET:
        q = request.GET['q']
        data = Product.objects.filter(Q(name__icontains=q) | Q(description__icontains=q))

        if data and q:
            data_q = 'True'
        elif data:
            data_q = 'TrueFalse'
        else:
            data_q = 'False'
    
    context = {
        'q': q,
        'data': data,
        'data_q': data_q
    }

    return render(request, 'search_products.html', context)

def category_search(request, slug):
    category_data = Category.objects.get(slug=slug)
    data = Product.objects.filter(category=category_data)

    return render(request, 'search_category.html', {'data': data})

def product_detail(request, slug):
    products = Product.objects.all().order_by('-create')[:10]
    product = Product.objects.filter(slug=slug).prefetch_related(
        'productcomment_set', 'items', 'productstar_set'
    )
    product = product.first()
    commet_count = ProductComment.objects.filter(product=product).count()

    context = {
        'product': product,
        'products': products,
        'commet_count': commet_count,
    }

    return render(request, 'detail.html', context)

def productItem_card(request, slug):
    return render(request, 'card.html')

def card(request):
    if 'cart' in request.session:
        card = request.session['cart']
        total_sum = 0
        for i in card.values():
            total_sum += Decimal(i['total'])
    else:
        total_sum = 0

    return render(request, 'card.html', {'total_sum': total_sum})

def card_add(request, slug, quantity):

    if 'quantity' in request.GET:
        quantity = request.GET['quantity']

    productitem = ProductItem.objects.get(slug=slug)
    if not request.session.get('cart'):
        request.session['cart'] = {}
    cart = request.session['cart']
    if not cart.get(str(productitem.id)):
        cart[str(productitem.id)] = {'quantity': 0, 'id': productitem.id, 
            'price': str(productitem.price), 'title': productitem.title, 'total': 0}
        request.session.modified = True
    
    if quantity:
        cart[str(productitem.id)]['quantity'] += int(quantity)
        cart[str(productitem.id)]['total'] = str(productitem.price * int(quantity))
    else:
        cart[str(productitem.id)]['quantity'] += 1
        cart[str(productitem.id)]['total'] = str(productitem.price)
        request.session.modified = True

    return redirect(request.META['HTTP_REFERER'])

def card_update(request, id):
    productitem = ProductItem.objects.get(id=id)
    quantity = 0
    if 'quantity' in request.GET:
        quantity = request.GET['quantity']
    cart = request.session['cart']
    cart[str(productitem.id)]['quantity'] = int(quantity)
    cart[str(productitem.id)]['total'] = str(productitem.price * int(quantity))
    request.session.modified = True
    return redirect('general:card')

def card_remove(request, id):
    productitem = ProductItem.objects.get(id=id)
    cart = request.session['cart']
    if str(productitem.id) in cart:
        del cart[str(productitem.id)]
    request.session.modified = True
    return redirect('general:card')

def card_clear(request):
    # remove cart from session
    del request.session['cart']
    request.session['cart'] = {}
    return redirect('general:card')

def checkout(request):

    delivery = Delivery.objects.first()
    shipping = delivery.price

    card = request.session['cart']
    total_sum = 0
    for i in card.values():
        total_sum += Decimal(i['total'])
    
    total = shipping + total_sum

    context = {
        'total_sum': total_sum,
        'shipping': shipping,
        'total': total,
    }
    return render(request, 'checkout.html', context)

def contact(request):
    shopabout = ShopAbout.objects.first()
    contactus = ContactUs.objects.all()

    if request.method == 'POST':
        user = User.objects.filter(username=request.POST.get('username')).first()
        if user:
            if user.email == request.POST.get('email'):
                contactquery = ContactQuery(
                    username=request.POST.get('username'),
                    email=request.POST.get('email'),
                    subject=request.POST.get('subject'),
                    text=request.POST.get('text'),
                )
                contactquery.save()
                messages.success(request, f'{contactquery.username} send message')
            else:
                messages.error(request, 'email sizga tegishli emas')
        else:
            messages.error(request, 'siz registeratsiyadan otmagansiz')
        
        return redirect('general:contact')
        


    context = {
        'shopabout': shopabout,
        'contactus': contactus,
    }
    return render(request, 'contact.html', context)

config/general/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>EShopper - Bootstrap Shop Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'shop/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'shop/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="{% url 'general:home' %}" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="{% url 'general:product_search' %}">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <button type="submit" class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="{% url 'wishlist:wishlist' %}" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">{{w_count}}</span>
                </a>
                <a href="{% url 'general:card' %}" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">{{ins}}</span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Categories</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                        {% for c in category %}
                            <a href="{% url 'general:category_search' c.slug %}" class="nav-item nav-link">{{c.title}}</a>
                        {% endfor %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">E</span>Shopper</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'general:home' %}" class="nav-item nav-link">Home</a>
                            <a href="{% url 'general:shop' %}" class="nav-item nav-link">Shop</a>
                            <a href="{% url 'general:contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                        {% if user.role == 'client' %}
                            <div class="navbar-nav ml-auto py-0">
                                <a href="{% url 'accounts:profile_home' %}" class="nav-item nav-link">Profile</a>
                                <a href="{% url 'accounts:user_logout' %}" class="nav-item nav-link">LOGOUT</a>
                            </div>
                        {% elif user.role == 'admin' %}
                            <div class="navbar-nav ml-auto py-0">
                                <a href="{% url 'accounts:profile_home' %}" class="nav-item nav-link">Profile</a>
                                <a href="{% url 'accounts:dashboard' %}" class="nav-item nav-link">Dashboard</a>
                                <a href="{% url 'accounts:user_logout' %}" class="nav-item nav-link">LOGOUT</a>
                            </div>
                        {% elif not request.user %}
                            <div class="navbar-nav ml-auto py-0">
                                <a href="{% url 'accounts:register' %}" class="nav-item nav-link">Login</a>
                                <a href="{% url 'accounts:user_login' %}" class="nav-item nav-link">Register</a>
                            </div>
                        {% endif %}
                    </div>
                </nav>
                {% block content_home %}
            
                {% endblock content_home %}
            </div>
        </div>
    </div>
    <!-- Navbar End -->

    {% block content %}
    
    {% endblock content %}

    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">E</span>Shopper</h1>
                </a>
                <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="{% static 'shop/img/payments.png' %}" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'shop/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'shop/lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'shop/mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'shop/mail/contact.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'shop/js/main.js' %}"></script>
    <script src="{% static 'shop/my_js.js' %}"></script>
</body>

</html>

config/general/templates/search_category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Products Start -->
    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Search Category</span></h2>
        </div>
        <div class="row px-xl-5 pb-3">
            {% for d in data %}
                <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100" src="{{d.get_first_item.image_medium}}" alt="">
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{d.get_first_item.title}}</h6>
                            <div class="d-flex justify-content-center">
                                <h6>${{d.get_first_item.price}}</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="{% url 'general:product_detail' d.slug %}" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                            <a href="{% url 'general:card_add' d.get_first_item.slug 1 %}" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                            <a href="{% url 'wishlist:wishlist_add' d.get_first_item.slug %}" class="btn btn-sm text-dark p-0">
                                <i class="fas fa-heart text-primary "></i>
                                <span class="badge"></span>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Products End -->

{% endblock content %}