config/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='register'),
    path('password_reset/', views.password_reset_request, name='password_reset'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard_clients/', views.dashboard_clients, name='dashboard_clients'),
    path('user_role/<int:pk>/', views.user_role, name='user_role'),
    path('profile_home/', views.profile_home, name='profile_home'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/<int:pk>/', views.profile_update, name='profile_update'),
    path('cardChange/<int:pk>', views.user_change_card, name='cardChange'),
    path('passChange/<int:pk>/', views.user_change_password, name='passChange'),
    path('addressChange/<int:pk>', views.user_change_address, name='addressChange'),
    path('user_delete/<int:pk>/', views.user_delete, name='user_delete'),
    path('', views.user_login, name='user_login'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('general/', include('general.urls', namespace='general')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    # path('discounts/', include('discounts.urls', namespace='discounts')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls')),
    path('wishlists/', include('wishlists.urls', namespace='wishlists')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),      
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('product', views.product, name='product'),
    path('productCreate', views.productCreate, name='productCreate'),
    path('productUpdate/<slug:slug>/', views.productUpdate, name='productUpdate'),
    path('productDelete/<slug:slug>/', views.productDelete, name='productDelete'),
    
    path('productItem', views.productItem, name='productItem'),
    path('productItemCreate', views.productItemCreate, name='productItemCreate'),
    path('productItemUpdate/<slug:slug>/', views.productItemUpdate, name='productItemUpdate'),
    path('productItemDelete/<slug:slug>/', views.productItemDelete, name='productItemDelete'),

    path('productColor', views.productColor, name='productColor'),
    path('productColorCreate', views.productColorCreate, name='productColorCreate'),
    path('productColorUpdate/<int:id>/', views.productColorUpdate, name='productColorUpdate'),
    path('productColorDelete/<int:id>/', views.productColorDelete, name='productColorDelete'),

    path('productSize', views.productSize, name='productSize'),
    path('productSizeCreate', views.productSizeCreate, name='productSizeCreate'),
    path('productSizeUpdate/<int:id>/', views.productSizeUpdate, name='productSizeUpdate'),
    path('productSizeDelete/<int:id>/', views.productSizeDelete, name='productSizeDelete'),

    path('brand', views.brand, name='brand'),
    path('brandCreate', views.brandCreate, name='brandCreate'),
    path('brandUpdate/<slug:slug>/', views.brandUpdate, name='brandUpdate'),
    path('brandDelete/<slug:slug>/', views.brandDelete, name='brandDelete'),

    path('category', views.category, name='category'),
    path('categoryCreate', views.categoryCreate, name='categoryCreate'),
    path('categoryUpdate/<slug:slug>/', views.categoryUpdate, name='categoryUpdate'),
    path('categoryDelete/<slug:slug>/', views.categoryDelete, name='categoryDelete'),

    path('productCommet/<slug:slug>/', views.productCommet, name='productCommet')
]

config/accounts/models.py
from django.db import models
from .servises import upload_avatar_path
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField

# Create your models here.

class User(AbstractUser):

    CHOICE_ROLE = (
        ('client', 'CLIENT'),
        ('admin', 'ADMIN'),
    )

    CHOICE_CURRENCY = (
        ('uzs', 'UZS'),
        ('usd', 'USD'),
        ('rub', 'RUB'),
    )

    CHOICE_CITY = (
        ('tashkent', 'TASHKENT'),
        ('surxondaryo', 'SURXONDARYO'),
    )

    CHOICE_REGION = (
        ('olmazor', 'OLMAZOR'),
        ('chilonzor', 'CHILONZOR'),
        ('kumkurgan', 'KUMKURGAN'),
        ('termiz', 'TERMIZ')
    )

    email = models.EmailField('email address', unique=True)
    phonenumber = PhoneNumberField(null=True, blank=True, unique=True)
    avatar = models.ImageField(upload_to=upload_avatar_path, default='profile/defaultadmin/defaultadmin.png')
    user_currency = models.CharField(max_length=3, choices=CHOICE_CURRENCY, default=CHOICE_CURRENCY[0][0])
    about = models.TextField(blank=True, null=True)
    role = models.CharField(max_length=6, choices=CHOICE_ROLE, default=CHOICE_ROLE[0][0])

    # Address

    country = CountryField(blank=True, null=True)
    city = models.CharField(max_length=20, choices=CHOICE_CITY)
    region = models.CharField(max_length=100, choices=CHOICE_REGION)
    zip_code = models.PositiveIntegerField(blank=True, null=True)
    address1 = models.CharField(max_length=250, blank=True)

    # Card

    card_number = models.PositiveIntegerField(blank=True, null=True)
    card_date = models.DateField(blank=True, null=True)
    currency = models.CharField(max_length=3, choices=CHOICE_CURRENCY, default=CHOICE_CURRENCY[0][0])

    def __str__(self):
        return self.username
    
class UserDataOnDelete(models.Model):
    first_name = models.CharField('first name', max_length=150)
    last_name = models.CharField('last name', max_length=150)
    username = models.CharField(max_length=128)
    role = models.CharField(max_length=6, choices=User.CHOICE_ROLE, default=User.CHOICE_ROLE[0][0])

    def __str__(self) -> str:
        return self.username

config/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate


class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=128)
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password1')
        

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=128)
    
    def user_auth(self):
        user = authenticate(**self.cleaned_data)
        if user:
            return user
        return None

class UserForm(forms.ModelForm):

    class Meta:
        model = User
        exclude = ('date_joined', 'last_login', 'groups', 'user_permissions')


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('avatar', 'username', 'first_name', 'last_name', 'about', 'user_currency', 'address1', 'phonenumber', 'email')

class UserCurrencyForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('user_currency',)

class UserCardChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('card_number', 'card_date', 'currency')

class UserChangePassword(forms.Form):
    password = forms.CharField(max_length=128)
    password1 = forms.CharField(max_length=128)
    password2 = forms.CharField(max_length=128)

class UserAddressForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('country', 'city', 'region', 'zip_code', 'address1')

class UserRoleForm(forms.ModelForm):
    
    class Meta:
        model = User
        fields = ('role',)

config/products/forms.py
from django import forms
from .models import *

class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'category', 'brand', 'author', 'description', 'is_active')

class ProductItemForm(forms.ModelForm):

    class Meta:
        model = ProductItem
        fields = ('title', 'product', 'author', 'price', 'size', 'color', 'count_in_stock', 'is_active', 'image')

class ProductColorForm(forms.ModelForm):

    class Meta:
        model = ProductColor
        fields = ('name', 'color', 'author')

class ProductSizeForm(forms.ModelForm):

    class Meta:
        model = ProductSize
        fields = ('name', 'size', 'author')

class ProductCommentForm(forms.ModelForm):

    class Meta:
        model = ProductComment
        fields = ('text', 'user', 'product')

class BrandForm(forms.ModelForm):

    class Meta:
        model = Brand
        fields = ('name', 'author', 'description', 'image')

class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('title', 'author', 'description', 'is_active', 'image')

config/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.contrib import messages
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.forms import PasswordResetForm
from django.db.models import Q
from .forms import *
from .models import User
from django.core.files import File
from django.conf import settings


# Create your views here.

def user_register(request):

    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():

            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            password1 = form.cleaned_data.get('password1')

            user = User.objects.filter(Q(username=username) | Q(email=email))
            
            if not user:
                if password == password1:
                    user = User(username = username, email=email)
                    user.set_password(password)
                    user.save()
                    return redirect('accounts:user_login')
                else:
                    messages.error(request, 'The password is not the same')
            else:
                messages.error(request, 'You are registered')
        else:
            messages.error(request, 'The form was filled in incorrectly')
    else:
        form = UserRegisterForm

    return render(request, 'sign_up.html', {'form':form})


def user_login(request):
    
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid() and form.user_auth():
            user = form.user_auth()
            login(request, user)
            return redirect('general:home')
        else:
            if form.errors:
                messages.error(request, form.errors)
            else:
                messages.error(request, 'You are not registered')
    else:
        form = UserLoginForm()

    return render(request, 'sign_in.html', {'form':form})


def password_reset_request(request):
    if request.method == 'POST':
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password_reset/password_reset_email.txt"
                    context = {
                        'email': user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'e_shop',
                        'uidb64': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user':user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, context)
                    try:
                        send_mail(subject ,email, 'mbpy2000@gmail.com', [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found')
                    return redirect('/password_reset/done/')
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name='password_reset/password_reset.html', context={'password_reset_form':password_reset_form})


def user_logout(request):
    logout(request)
    return redirect('accounts:user_login')


def dashboard(request):
    user = request.user
    context = {
        'user': user,
    }
    return render(request, 'dashboard/dashboard_index.html', context)


def dashboard_clients(request):

    users = []
    for user in User.objects.all():
        if user.role == 'client':
            users.append(user)
    context = {
        'users': users,
    }

    return render(request, 'dashboard/clients.html', context)

def user_role(request, pk):
    user1 = User.objects.get(id=pk)
    users = []
    form = UserRoleForm()
    for user in User.objects.all():
        if user.role == 'client':
            users.append(user)

    if request.method == 'POST':
        form = UserRoleForm(request.POST, instance=user1)
        if form.is_valid():
            form.save()
            return redirect('accounts:dashboard_clients')
        else:
            messages.error(request, form.errors)
    
    context = {
        'user1':user1,
        'form':form,
        'users': users,
    }

    return render(request, 'dashboard/clients.html', context)

def profile_home(request):
    user = request.user
    context = {
        'user': user,
    }
    return render(request, 'profile/user_profile_index.html', context)


@login_required(login_url='accounts:user_login')
def profile(request):

    user = request.user
    currency_form = UserCurrencyForm(instance=user)
    card_form = UserCardChangeForm(instance=user)
    pass_form = UserChangePassword()
    address_form = UserAddressForm(instance=user)

    context = {
            'user': user,
            'card_form': card_form,
            'currency_form': currency_form,
            'pass_form': pass_form,
            'address_form': address_form,
        }

    return render(request, 'profile/user_profile.html', context)


def profile_update(request, pk):
    form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
            
    if form.is_valid():
        user = form.save(commit=False)
        if request.POST.get('delete_avatar'):
            form.cleaned_data['avatar'] = None
            user.avatar.save(
                'defaultadmin.png', File(open(settings.DEFAULT_AVATAR_URL, 'rb'))
            )
        user.save()
    else:
        messages.error(request, form.errors)

    return redirect('accounts:profile')


def user_change_card(request, pk):

    card1_form = UserCardChangeForm(request.POST, instance=request.user)
    if card1_form.is_valid():
        card1_form.save()
        messages.success(request, 'Card information has changed')
    else:
        messages.error(request, card1_form.errors)
    
    return redirect('accounts:profile')


def user_change_password(request, pk):
    
    pass_form = UserChangePassword(request.POST)
    if pass_form.is_valid():
        user = User.objects.get(username=request.user)
        if user.check_password(pass_form.cleaned_data['password']):
            if pass_form.cleaned_data['password1'] == pass_form.cleaned_data['password2']:
                user.set_password(pass_form.cleaned_data['password2'])
                user.save()
                messages.success(request, 'Password changed successfully!')
            else:
                messages.error(request, 'New passwords don\'t similar!')
        else:
            messages.error(request, 'The old password was entered incorrectly!')
    else:
        messages.error(request, pass_form.errors)
    
    return redirect('accounts:profile')


def user_change_address(request, pk):

    address_form = UserAddressForm(request.POST, instance=request.user)
    if address_form.is_valid():
        address_form.save()
        messages.success(request, 'Address changed successfully')
    else:
        messages.error(request, address_form.errors)
    
    return redirect('accounts:profile')



def user_delete(request, pk):
    
    user = get_object_or_404(User, id=pk)
    if request.POST:
        user.delete()
        return redirect('general:home')

    return render(request, 'user_delete.html')

config/accounts/templates/dashboard/brand_create.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Brand Create</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">PRODUCTS</li>
          <li class="breadcrumb-item active">Brands</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        {% for msg in messages %}
          {{msg}}
        {% endfor %}
        <div class="col-lg-9">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Brand Create Form</h5>

              <!-- General Form Elements -->
              <form method='post' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row mb-3">
                  <label for="inputText" class="col-sm-2 col-form-label">Name</label>
                  <div class="col-sm-10">
                    <input type="text" name="name" class="form-control">
                  </div>
                </div>
                <div class="row mb-3">
                  <label class="col-sm-2 col-form-label">Author</label>
                  <div class="col-sm-10">
                    <select class="form-select" name="author" aria-label="Default select example">
                      {% for id, name in brand_form.author.field.choices %}
                        <option value="{{id}}">{{name}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="row mb-3">
                  <label for="inputPassword" class="col-sm-2 col-form-label">Description</label>
                  <div class="col-sm-10">
                    <textarea name="description" class="form-control" style="height: 100px"></textarea>
                  </div>
                </div>
                <div class="row mb-3">
                    <label for="inputNumber" class="col-sm-2 col-form-label">Image</label>
                    <div class="col-sm-10">
                      <input class="form-control" name="image" type="file" id="formFile">
                    </div>
                </div>
                <div class="row mb-3">
                  <label class="col-sm-4 col-form-label">Submit Button</label>
                  <div class="col-sm-8">
                    <input type="submit" class="btn btn-primary" value="---- Submit ----">
                  </div>
                </div>

              </form><!-- End General Form Elements -->

            </div>
          </div>
        </div>
      </div>
    </section>

  </main><!-- End #main -->

{% endblock content %}

config/accounts/templates/dashboard/clients.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">Users</li>
          <li class="breadcrumb-item active">clients</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">

          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                {% for user1 in users %}
                    <h4><a href="{% url 'accounts:user_role' user1.id %}">{{user1.username}}</a></h4>
                {% endfor %}
            </div>
          </div>

        </div>

        <div class="col-xl-8">

          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">

                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-cards">Cards</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-role">Change Role</button>
                </li>

                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-address">Address</button>
                </li>

              </ul>
              <div class="tab-content pt-2">

                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                  <div class="col-md-8 col-lg-9">
                    <img src="{{user1.avatar.url}}" alt="Profile" width="100px">
                    <a href="{{ user1.avatar.url }}">{{ user1.avatar.url }}</a>
                  </div>
                  <h5 class="card-title">About</h5>
                  <p class="small fst-italic">{{user1.about}}</p>

                  <h5 class="card-title">Profile Details</h5>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Full Name</div>
                    <div class="col-lg-9 col-md-8">{{user1.first_name}} {{user1.last_name}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Phone</div>
                    <div class="col-lg-9 col-md-8">{{user1.phonenumber}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div class="col-lg-9 col-md-8">{{user1.email}}</div>
                  </div>

                </div>

                <div class="tab-pane fade profile-edit pt-3" id="profile-cards">

                  <!-- Cards -->
                  
                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Card Number</div>
                    <div class="col-lg-9 col-md-8">{{user1.card_number}}</div>
                  </div>


                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Validity Period</div>
                    <div class="col-lg-9 col-md-8">{{user1.card_date}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Currency</div>
                    <div class="col-lg-9 col-md-8">{{user1.get_currency_display}}</div>
                  </div>

                </div>

                <div class="tab-pane fade pt-3" id="profile-change-role">

                  <!-- Settings Form -->
                  <form method='post'>
                    {% csrf_token %}
                        <div class="row mb-3">
                            <h3>{{form}}</h3>
                        </div>

                        <div class="text-center">
                            <input type="submit" class="btn btn-primary" value="Save Changes">
                        </div>
                  </form><!-- End settings Form -->

                </div>

                <div class="tab-pane fade pt-3" id="profile-address">
                  <!-- Address -->
                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Country</div>
                    <div class="col-lg-9 col-md-8">{{user1.get_country_display}}</div>
                  </div>


                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">City</div>
                    <div class="col-lg-9 col-md-8">{{user1.get_city_display}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Region</div>
                    <div class="col-lg-9 col-md-8">{{user1.region}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Zip Code</div>
                    <div class="col-lg-9 col-md-8">{{user1.zip_code}}</div>
                  </div>

                  <div class="row">
                    <div class="col-lg-3 col-md-4 label text-primary">Full Address</div>
                    <div class="col-lg-9 col-md-8">{{user1.address1}}</div>
                  </div>
                </div>

              </div><!-- End Bordered Tabs -->

            </div>
          </div>

        </div>
      </div>
    </section>

  </main><!-- End #main -->

{% endblock content %}

config/accounts/templates/dashboard/productColor.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>ProductColors</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">PRODUCTS</li>
          <li class="breadcrumb-item active">ProductColors</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <div class="tm-product-table-container">
        {% for msg in messages %}
          {{msg}}
        {% endfor %}
        <form method="get" action="">
          {% csrf_token %}
          <table class="table table-hover tm-table-small tm-product-table">
              <thead>
                  <tr>
                      <th scope="col">&nbsp;</th>
                      <th scope="col">NAME</th>
                      <th scope="col">COLOR</th>
                      <th scope="col">AUTHOR</th>
                      <th>
                          <a href="{% url 'products:productColorCreate' %}" class="btn btn-primary btn-block text-uppercase">Add new productColor</a>
                      </th>
                  </tr>
              </thead>
              <tbody>
                  {% for productColor in productColors %}
                      <tr>
                          <th scope="row"><input type="checkbox" name="{{productColor.id}}"></th>
                          <td class="tm-product-name">{{productColor.name}}</td>
                          <td>{{productColor.color}}</td>
                          <td>{{productColor.author}}</td>
                          <td>
                          <a href="{% url 'products:productColorUpdate' id=productColor.id %}" class="create-link">UPDATE</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          <a href="{% url 'products:productColorDelete' id=productColor.id %}" class="create-link">DELETE</a>
                          </td>
                      </tr>
                  {% endfor %}
              </tbody>
          </table>
          <button class="btn btn-primary btn-block text-uppercase"> Delete selected productColors</button>
        </form>
        </div>

  </main><!-- End #main -->
    

{% endblock content %}

config/accounts/templates/dashboard/productSize.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block content %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>ProductSizes</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item">PRODUCTS</li>
          <li class="breadcrumb-item active">ProductSizes</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <div class="tm-product-table-container">
        {% for msg in messages %}
          {{msg}}
        {% endfor %}
        <form method="get" action="">
          {% csrf_token %}
          <table class="table table-hover tm-table-small tm-product-table">
              <thead>
                  <tr>
                      <th scope="col">&nbsp;</th>
                      <th scope="col">NAME</th>
                      <th scope="col">SIZE</th>
                      <th scope="col">AUTHOR</th>
                      <th>
                          <a href="{% url 'products:productSizeCreate' %}" class="btn btn-primary btn-block text-uppercase">Add new productSize</a>
                      </th>
                  </tr>
              </thead>
              <tbody>
                  {% for productSize in productSizes %}
                      <tr>
                          <th scope="row"><input type="checkbox" name="{{productSize.id}}"></th>
                          <td class="tm-product-name">{{productSize.name}}</td>
                          <td>{{productSize.size}}</td>
                          <td>{{productSize.author}}</td>
                          <td>
                          <a href="{% url 'products:productSizeUpdate' id=productSize.id %}" class="create-link">UPDATE</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                          <a href="{% url 'products:productSizeDelete' id=productSize.id %}" class="create-link">DELETE</a>
                          </td>
                      </tr>
                  {% endfor %}
              </tbody>
          </table>
          <button class="btn btn-primary btn-block text-uppercase"> Delete selected productColors</button>
        </form>
        </div>

  </main><!-- End #main -->
    

{% endblock content %}