config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('general/', include('general.urls', namespace='general')),
    path('deliveries/', include('deliveries.urls', namespace='deliveries')),
    # path('discounts/', include('discounts.urls', namespace='discounts')),
    # path('orders/', include('orders.urls', namespace='orders')),
    path('products/', include('products.urls')),
    path('wishlists/', include('wishlists.urls', namespace='wishlists')),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password_reset/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),      
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/general/urls.py
from django.urls import path
from . import views

app_name = 'general'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop_product_search/', views.shop_product_search, name='shop_product_search'),
    path('product_search/', views.product_search, name="product_search"),
    path('category_search/<slug:slug>/', views.category_search, name="category_search"),
    path('product_detail/<slug:slug>/', views.product_detail, name="product_detail"),
    path('productItem_card/<slug:slug>/', views.productItem_card, name="productItem_card"),
    path('card/', views.card, name='card'),
    path('card_add/<slug:slug>/<int:quantity>/', views.card_add, name='card_add'),
    path('card_remove/<int:id>/', views.card_remove, name='card_remove'),
    path('card_update/<int:id>/', views.card_update, name='card_update'),
    path('card_clear/', views.card_clear, name='card_clear'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
]

config/wishlists/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist_add/<slug:slug>/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/<int:id>/', views.wishlist_delete, name='wishlist_delete'),
]

config/wishlists/models.py
from django.db import models
from accounts.models import User, UserDataOnDelete
from products.models import ProductItem
from accounts.validators import is_client
from django.core.exceptions import ValidationError

# Create your models here.

class Wishlist(models.Model):

    product = models.ForeignKey(ProductItem, on_delete=models.CASCADE)
    client = models.ForeignKey(User, validators=[is_client], related_name='wishlist_client', on_delete=models.CASCADE)
    author_data = models.ForeignKey(UserDataOnDelete, on_delete=models.PROTECT, blank=True, null=True)

    def clean(self):
        if self.author and self.author_data:
            raise ValidationError({'{author_data}': 'Filling is not required'})

    class Meta:
        unique_together = ['product', 'client']

config/wishlists/forms.py
from django import forms 
from .models import Wishlist

class WishlistForm(forms.ModelForm):
    pass

config/wishlists/views.py
from django.shortcuts import render, redirect
from products.models import ProductItem
from .models import Wishlist
from django.contrib import messages

# Create your views here.

def wishlist(request):
    user = request.user
    data = Wishlist.objects.filter(client=user)
    return render(request, 'wishlist.html', {'data': data})

def wishlist_add(request, slug):

    productitem = ProductItem.objects.get(slug=slug)
    user = request.user
    if user.role == 'client':
        wishlist = Wishlist.objects.filter(product=productitem)
        if not wishlist:
            wishlist = Wishlist(
                product=productitem,
                client=user,
            )
            wishlist.save()
        else:
            messages.error(request, 'Bu product wishlistga qo\'shilgan')
    else:
        messages.error(request, 'you are admin')
    return redirect(request.META['HTTP_REFERER'])

def wishlist_delete(request, id):
    wishlist = Wishlist.objects.get(id=id)
    wishlist.delete()
    return redirect('wishlist:wishlist')

config/wishlists/templates/wishlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Products Start -->
    <div class="container-fluid pt-5">
        <div class="text-center mb-4">
            <h2 class="section-title px-5"><span class="px-2">Wishlist Products</span></h2>
        </div>
        <div class="row px-xl-5 pb-3">
            {% for d in data %}
                <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                    <div class="card product-item border-0 mb-4">
                        <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                            <img class="img-fluid w-100" src="{{d.product.image_medium}}" alt="">
                        </div>
                        <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                            <h6 class="text-truncate mb-3">{{d.product.title}}</h6>
                            <div class="d-flex justify-content-center">
                                <h6>${{d.product.price}}</h6><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                            </div>
                        </div>
                        <div class="card-footer d-flex justify-content-between bg-light border">
                            <a href="{% url 'general:product_detail' d.product.product.slug %}" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-primary mr-1"></i>View Detail</a>
                            <a href="{% url 'general:productItem_card' d.product.slug %}" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-primary mr-1"></i>Add To Cart</a>
                            <a href="{% url 'wishlist:wishlist_delete' d.id %}" class="btn btn-sm text-dark p-0">
                                <i class="fas fa-trash text-primary "></i>
                                <span class="badge"></span>
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- Products End -->

{% endblock content %}